/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RemoteConnector.h>
#include <WiFi.h>
#include "EthernetTransport.h"
#include "tcMenuU8g2.h"

// all define statements needed
#define TCMENU_USING_PROGMEM true

// all variables that need exporting
extern U8G2_SSD1306_128X64_NONAME_F_SW_I2C gfx;
extern U8g2MenuRenderer renderer;
extern const char applicationName[];

// all menu item forward references.
extern ActionMenuItem menuSaveAll;
extern EnumMenuItem menuWinOpening;
extern EnumMenuItem menuHeaterPower;
extern BackMenuItem menuBackSetup;
extern SubMenuItem menuSetup;
extern BooleanMenuItem menuElectricHeater;
extern BooleanMenuItem menuWindowOpen;
extern AnalogMenuItem menuCucumberTemp;
extern AnalogMenuItem menuTomatoTemp;

// Callback functions always follow this pattern: void CALLBACK_FUNCTION myCallback();
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onWindowOpen(int id);
void CALLBACK_FUNCTION onElectricHeater(int id);
void CALLBACK_FUNCTION onHeaterPower(int id);
void CALLBACK_FUNCTION onWindowOpening(int id);
void CALLBACK_FUNCTION onSaveAll(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
