/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include "tcMenuU8g2.h"
#include "EthernetTransport.h"
#include <RemoteConnector.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern U8G2_SSD1306_128X64_NONAME_F_SW_I2C gfx;
extern U8g2GfxMenuConfig gfxConfig;
extern U8g2MenuRenderer renderer;
extern IoAbstractionRef io8574;
extern WiFiServer server;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

extern IpAddressMenuItem menuIpAddress;
extern TextMenuItem menuPwd;
extern TextMenuItem menuSSID;
extern SubMenuItem menuConnectivity;
void CALLBACK_FUNCTION onSaveAll(int id);
extern ActionMenuItem menuSaveAll;
void CALLBACK_FUNCTION onWindowOpening(int id);
extern EnumMenuItem menuWinOpening;
void CALLBACK_FUNCTION onHeaterPower(int id);
extern EnumMenuItem menuHeaterPower;
extern SubMenuItem menuSetup;
void CALLBACK_FUNCTION onElectricHeater(int id);
extern BooleanMenuItem menuElectricHeater;
void CALLBACK_FUNCTION onWindowOpen(int id);
extern BooleanMenuItem menuWindowOpen;
extern AnalogMenuItem menuCucumberTemp;
extern AnalogMenuItem menuTomatoTemp;

#endif // MENU_GENERATED_CODE_H
