/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <SSD1306Ascii.h>
#include <RuntimeMenuItem.h>
#include <SSD1306AsciiAvrI2c.h>
#include "ssd1306asciiRenderer.h"
#include <RemoteConnector.h>
#include "SerialTransport.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern SSD1306AsciiAvrI2c gfx;
extern SSD1306AsciiRenderer renderer;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

int fnListItemRtCall(RuntimeMenuItem * item, uint8_t row, RenderFnMode mode, char * buffer, int bufferSize);
extern ListRuntimeMenuItem menuListItem;
extern AnalogMenuItem menuStatusTemprature;
extern FloatMenuItem menuStatusVoltageIn;
extern FloatMenuItem menuStatusPowerUse;
extern SubMenuItem menuStatus;
void CALLBACK_FUNCTION onActionPressed(int id);
extern ActionMenuItem menuPressMe;
extern BooleanMenuItem menuStandby;
extern AnalogMenuItem menuBlue;
extern AnalogMenuItem menuGreen;
extern AnalogMenuItem menuRed;
extern AnalogMenuItem menuBrightness;

#endif // MENU_GENERATED_CODE_H
