/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <SSD1306Ascii.h>
#include <SSD1306AsciiAvrI2c.h>
#include "ssd1306asciiRenderer.h"
#include <DfRobotInputAbstraction.h>
#include <RuntimeMenuItem.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern SSD1306AsciiAvrI2c gfx;
extern SSD1306AsciiRenderer renderer;

// Global Menu Item exports
extern ListRuntimeMenuItem menuListItem;
extern AnalogMenuItem menuStatusTemprature;
extern FloatMenuItem menuStatusVoltageIn;
extern FloatMenuItem menuStatusPowerUse;
extern BackMenuItem menuBackStatus;
extern SubMenuItem menuStatus;
extern ActionMenuItem menuPressMe;
extern BooleanMenuItem menuStandby;
extern AnalogMenuItem menuBlue;
extern AnalogMenuItem menuGreen;
extern AnalogMenuItem menuRed;
extern AnalogMenuItem menuBrightness;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuBrightness; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnListItemRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onActionPressed(int id);

#endif // MENU_GENERATED_CODE_H
