/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include <LiquidCrystalIO.h>
#include "EthernetTransport.h"
#include <RemoteConnector.h>
#include <EditableLargeNumberMenuItem.h>
#include "tcMenuLiquidCrystal.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern IoAbstractionRef io23017;
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;
extern IoAbstractionRef io23017;
extern EthernetServer server;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

void CALLBACK_FUNCTION onSaveToEeprom(int id);
extern ActionMenuItem menuConnectivitySaveToEEPROM;
extern TextMenuItem menuConnectivityText;
extern IpAddressMenuItem menuConnectivityIpAddress;
void CALLBACK_FUNCTION onChangePin(int id);
extern TextMenuItem menuConnectivityChangePin;
extern SubMenuItem menuConnectivity;
extern EnumMenuItem menuFruits;
void CALLBACK_FUNCTION onFiths(int id);
extern AnalogMenuItem menuFiths;
extern EditableLargeNumberMenuItem menuLargeNum;
extern AnalogMenuItem menuDecimalTens;
void CALLBACK_FUNCTION onInteger(int id);
extern AnalogMenuItem menuInteger;
extern BooleanMenuItem menuHiddenItem;
void CALLBACK_FUNCTION onAnalog1(int id);
extern AnalogMenuItem menuAnalog1;
extern TimeFormattedMenuItem menuTime;

#endif // MENU_GENERATED_CODE_H
