/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include <LiquidCrystalIO.h>
#include "tcMenuLiquidCrystal.h"
#include <DfRobotInputAbstraction.h>
#include <EditableLargeNumberMenuItem.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

extern TextMenuItem menuText;
extern EditableLargeNumberMenuItem menuLgeNum;
void CALLBACK_FUNCTION onLed2(int id);
extern BooleanMenuItem menuLED2;
void CALLBACK_FUNCTION onLed1(int id);
extern BooleanMenuItem menuLED1;
extern SubMenuItem menuLEDStates;
extern AnalogMenuItem menuValueA0;

#endif // MENU_GENERATED_CODE_H
