/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include "tcMenuLiquidCrystal.h"
#include <LiquidCrystalIO.h>
#include <IoAbstraction.h>
#include <DfRobotInputAbstraction.h>
#include "RemoteConnector.h"

// all define statements needed


// all variables that need exporting
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;
extern const char applicationName[];

// all menu item forward references.
extern BooleanMenuItem menuLED2;
extern BooleanMenuItem menuLED1;
extern BackMenuItem menuBackLEDStates;
extern SubMenuItem menuLEDStates;
extern AnalogMenuItem menuValueA0;

// Callback functions always follow this pattern: void CALLBACK_FUNCTION myCallback();
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onLed1(int id);
void CALLBACK_FUNCTION onLed2(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
