/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

// PLUGIN FILE - tcMenuU8g2.h
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * @file tcMenuU8g2.h
 * 
 * U8g2 renderer that renders menus onto this type of display. This file is a plugin file and should not
 * be directly edited, it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 * 
 * LIBRARY REQUIREMENT
 * This library requires the u8g2 library available for download from your IDE library manager.
 */

#ifndef _TCMENU_U8G2_H_
#define _TCMENU_U8G2_H_

#include <tcMenu.h>
#include <tcUtil.h>
#include <Wire.h>
#include <U8g2lib.h>
#include <graphics/BaseGraphicalRenderer.h>
#include <graphics/GraphicsDeviceRenderer.h>
#include <BaseDialog.h>
#include <tcUtil.h>


// If you DONT want task manager yield code in I2C set to 0
#ifndef WANT_TASK_MANAGER_FRIENDLY_YIELD
#define WANT_TASK_MANAGER_FRIENDLY_YIELD 1
#endif // WANT_TASK_MANAGER_FRIENDLY_YIELD

using namespace tcgfx;

/**
 * A standard menu render configuration that describes how to renderer each item and the title.
 * Specialised for u8g2 fonts.
 */
typedef struct ColorGfxMenuConfig<const uint8_t*> U8g2GfxMenuConfig;

// some colour displays don't create this value
#ifndef BLACK
#define BLACK 0
#endif

// some colour displays don't create this value
#ifndef WHITE
#define WHITE 1
#endif

/**
 * This is used to draw to I2C including a task manager yield to improve performance on slower I2C devices.
 * Not really needed for SPI as we are talking in low order millis for a full refresh.
 */
uint8_t u8g2_byte_with_yield(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);

/**
 * A basic renderer that can use the AdaFruit_GFX library to render information onto a suitable
 * display. It is your responsibility to fully initialise and prepare the display before passing
 * it to this renderer. The usual procedure is to create a display variable globally in your
 * sketch and then provide that as the parameter to setGraphicsDevice. If you are using the
 * designer you provide the display variable name in the code generation parameters.
 *
 * You can also override many elements of the display using AdaColorGfxMenuConfig, to use the defaults
 * just call prepareAdaColorDefaultGfxConfig(..) passing it a pointer to your config object. Again the
 * designer UI takes care of this.
 */
class U8g2Drawable : public DeviceDrawable {
private:
	U8G2* u8g2;
#if WANT_TASK_MANAGER_FRIENDLY_YIELD == 1
    static TwoWire* pWire;
    friend uint8_t u8g2_byte_with_yield(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr);
#endif // WANT_TASK_MANAGER_FRIENDLY_YIELD
public:
    explicit U8g2Drawable(U8G2* u8g2, TwoWire* wire = nullptr);
    ~U8g2Drawable() override = default;

    DeviceDrawable* getSubDeviceFor(const Coord &where, const Coord &size, const color_t *palette, int paletteSize) override {return nullptr; }

    void internalDrawText(const Coord &where, const void *font, int mag, const char *text) override;
    void drawBitmap(const Coord &where, const DrawableIcon *icon, bool selected) override;
    void drawXBitmap(const Coord &where, const Coord &size, const uint8_t *data) override;
    void drawBox(const Coord &where, const Coord &size, bool filled) override;
    void drawCircle(const Coord &where, int radius, bool filled) override;
    void drawPolygon(const Coord *points, int numPoints, bool filled) override;

    Coord getDisplayDimensions() override {  return Coord(u8g2->getWidth(), u8g2->getHeight()); }
    void transaction(bool isStarting, bool redrawNeeded) override;
    Coord internalTextExtents(const void *font, int mag, const char *text, int *baseline) override;
    color_t getUnderlyingColor(color_t col) override { return (col<4) ? col : 1; }
protected:
    void drawPixel(uint16_t x, uint16_t y) override;
    UnicodeFontHandler *createFontHandler() override;
};

#endif // _TCMENU_U8G2_H_


// PLUGIN FILE - EthernetTransport.h
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * @file EthernetTransport.h
 * 
 * Ethernet remote capability plugin. This file is a plugin file and should not be directly edited,
 * it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 */

#ifndef TCMENU_ETHERNETTRANSPORT_H_
#define TCMENU_ETHERNETTRANSPORT_H_

#include <RemoteConnector.h>
#include <TaskManager.h>
#include <Ethernet.h>
#include <tcUtil.h>
#include <remote/BaseRemoteComponents.h>

#ifndef ETHERNET_BUFFER_SIZE
#define ETHERNET_BUFFER_SIZE 64
#endif

#if ETHERNET_BUFFER_SIZE > 0
#include <remote/BaseBufferedRemoteTransport.h>
#endif

namespace tcremote {

#if ETHERNET_BUFFER_SIZE > 0

/**
 * An implementation of TagValueTransport that is able to read and write via a buffer to sockets.
 */
    class EthernetTagValTransport : public tcremote::BaseBufferedRemoteTransport {
    private:
        EthernetClient client;
    public:
        EthernetTagValTransport() : BaseBufferedRemoteTransport(BUFFER_MESSAGES_TILL_FULL, ETHERNET_BUFFER_SIZE, MAX_VALUE_LEN) { }
        ~EthernetTagValTransport() override = default;
        void setClient(EthernetClient cl) { this->client = cl; }

        int fillReadBuffer(uint8_t* data, int maxSize) override;
        void flush() override;
        bool available() override;
        bool connected() override;
        void close() override;
    };

#else // ethernet buffering not needed

/**
 * An implementation of TagValueTransport that is able to read and write using sockets.
 */
class EthernetTagValTransport : public TagValueTransport {
private:
	EthernetClient client;
public:
	EthernetTagValTransport() : TagValueTransport(TagValueTransportType::TVAL_UNBUFFERED) {};
	~EthernetTagValTransport() override = default;
	void setClient(EthernetClient client) { this->client = client; }

	int writeChar(char data) override ;
	int writeStr(const char* data) override;
	void flush() override;
	bool available() override;
	bool connected() override;
	uint8_t readByte() override;
	bool readAvailable() override;
    void close() override;
};

#endif // ethernet buffering check

/**
 * This class provides the initialisation and connection generation logic for ethernet connections.
 */
class EthernetInitialisation : public DeviceInitialisation {
private:
	EthernetServer *server;
public:
    explicit EthernetInitialisation(EthernetServer* server) : server(server) {}

    bool attemptInitialisation() override;

    bool attemptNewConnection(BaseRemoteServerConnection *transport) override;
};

/**
 * This function converts from a RSSI (Radio Strength indicator)
 * measurement into a series of icons (of the ones we have defined
 * in the stock icons. The input is the RSSI figure in dB as an
 * integer.
 * @param strength the signal strength (usually negative) as an int
 * @return a state that can be used with the standard wifi TitleWidget
 */
int fromWiFiRSSITo4StateIndicator(int strength);

} // namespace tcremote

#ifndef TC_MANUAL_NAMESPACING
using namespace tcremote;
#endif // TC_MANUAL_NAMESPACING

#endif /* TCMENU_ETHERNETTRANSPORT_H_ */

#include <Arduino.h>
#include <tcMenu.h>

#include <tcMenuBuilder.h>
#include <tcUnicodeHelper.h>
#include <RemoteConnector.h>
#include <ScrollChoiceMenuItem.h>
#include <RemoteMenuItem.h>
#include <IoAbstractionWire.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <EepromAbstractionWire.h>
#include <RemoteAuthentication.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern U8G2_SH1106_128X64_NONAME_F_HW_I2C gfx;
extern U8g2Drawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern EthernetServer server;
extern EthernetInitialisation ethernetInitialisation;
extern const UnicodeFont OpenSansRegular7pt[];
extern const UnicodeFont OpenSansRegular8pt[];

// Any externals needed by IO expanders, EEPROMs etc
extern IoAbstractionRef ioexp_io8574;

// The following defines all menu item IDs.
#define MENU_KITCHEN_ID  1
#define MENU_LOUNGE_ID  2
#define MENU_HALLWAY_ID  3
#define MENU_SETTINGS_ID  4
#define MENU_SETTINGS_TEMP_DESIRED_ID  5
#define MENU_SETTINGS_MODE_ID  6
#define MENU_SETTINGS_PROTECTION_ID  7
#define MENU_SETTINGS_EMERGENCY_OFF_ID  8
#define MENU_OTHER_TYPES_ID  9
#define MENU_OTHER_TYPES_TEXT_ID  10
#define MENU_OTHER_TYPES_R_G_B_ITEM_ID  11
#define MENU_OTHER_TYPES_FOODS_ID  12
#define MENU_IO_T_SETUP_ID  13
#define MENU_I_P_ADDRESS_ID  16
#define MENU_IO_T_MONITOR_ID  17
#define MENU_AUTHENTICATOR_ID  18

// Inline helper methods to access menu items
inline AnalogMenuItem& getMenuKitchen() { return getAnalogItemById(MENU_KITCHEN_ID); }
inline AnalogMenuItem& getMenuLounge() { return getAnalogItemById(MENU_LOUNGE_ID); }
inline AnalogMenuItem& getMenuHallway() { return getAnalogItemById(MENU_HALLWAY_ID); }
inline SubMenuItem& getMenuSettings() { return getSubMenuById(MENU_SETTINGS_ID); }
inline AnalogMenuItem& getMenuTempDesired() { return getAnalogItemById(MENU_SETTINGS_TEMP_DESIRED_ID); }
inline EnumMenuItem& getMenuMode() { return getEnumItemById(MENU_SETTINGS_MODE_ID); }
inline BooleanMenuItem& getMenuProtection() { return getBooleanItemById(MENU_SETTINGS_PROTECTION_ID); }
inline ActionMenuItem& getMenuEmergencyOff() { return getActionItemById(MENU_SETTINGS_EMERGENCY_OFF_ID); }
inline SubMenuItem& getMenuOtherTypes() { return getSubMenuById(MENU_OTHER_TYPES_ID); }
inline TextMenuItem& getMenuText() { return getTextItemById(MENU_OTHER_TYPES_TEXT_ID); }
inline Rgb32MenuItem& getMenuRGBItem() { return getRgb32ItemById(MENU_OTHER_TYPES_R_G_B_ITEM_ID); }
inline ScrollChoiceMenuItem& getMenuFoods() { return getScrollChoiceItemById(MENU_OTHER_TYPES_FOODS_ID); }
inline SubMenuItem& getMenuIoTSetup() { return getSubMenuById(MENU_IO_T_SETUP_ID); }
inline IpAddressMenuItem& getMenuIPAddress() { return getIpAddressItemById(MENU_I_P_ADDRESS_ID); }
inline RemoteMenuItem& getMenuIoTMonitor() { return getIoTRemoteMenuById(MENU_IO_T_MONITOR_ID); }
inline EepromAuthenticationInfoMenuItem& getMenuAuthenticator() { return getAuthenticationMenuById(MENU_AUTHENTICATOR_ID); }


// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return getMenuKitchen(); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION


#endif // MENU_GENERATED_CODE_H
