/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <LiquidCrystalIO.h>
#include <JoystickSwitchInput.h>
#include "tcMenuLiquidCrystal.h"

// all define statements needed
#define TCMENU_USING_PROGMEM true

// all variables that need exporting
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;
extern ArduinoAnalogDevice analogDevice;

// all menu item forward references.
extern FloatMenuItem menuFlow3;
extern FloatMenuItem menuFlow2;
extern FloatMenuItem menuFlow1;
extern BackMenuItem menuBackFlows;
extern SubMenuItem menuFlows;
extern BooleanMenuItem menuOverrideAll;
extern AnalogMenuItem menuTideGate3;
extern AnalogMenuItem menuTideGate2;
extern AnalogMenuItem menuTideGate1;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onTidalGate1(int id);
void CALLBACK_FUNCTION onTidalGate2(int id);
void CALLBACK_FUNCTION onTidalGate3(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
