/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include<IoAbstraction.h>
#include<Wire.h>
#include<tcMenu.h>

#include <Wire.h>
#include "tcMenuLiquidCrystal.h"
#include <IoAbstractionWire.h>
#include "RemoteConnector.h"

// all export definitions
extern IoAbstractionRef io23017;
#define ENCODER_PIN_A 6
#define ENCODER_PIN_B 7
#define ENCODER_PIN_OK 5

extern IoAbstractionRef io23017;
#define LCD_RS 8
#define LCD_EN 9
#define LCD_D4 10
#define LCD_D5 11
#define LCD_D6 12
#define LCD_D7 13
#define LCD_WIDTH 20
#define LCD_HEIGHT 4
#define LCD_PWM_PIN 5
#define LCD_I2C_ADDR 0x20
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

extern const char applicationName[];


// all menu item forward references.
extern TextMenuItem menuText;
extern ActionMenuItem menuSaveSettings;
extern AnalogMenuItem menuPower;
extern BooleanMenuItem menuEnabled;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern EnumMenuItem menuFood;
extern ActionMenuItem menuTakeDisplay;

// all callback functions must have this define on them, it is what the menu designer looks for.
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onTakeOverDisplay(int id);
void CALLBACK_FUNCTION onFoodChoice(int id);
void CALLBACK_FUNCTION onSaveSettings(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
