/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

// PLUGIN FILE - tcMenuTfteSpi.h
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * TFT_eSPI renderer that renders menus onto this type of display. This file is a plugin file and should not
 * be directly edited, it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 */

#ifndef TCMENU_PLUGIN_TCMENUTFTESPI_H
#define TCMENU_PLUGIN_TCMENUTFTESPI_H

#include <Arduino.h>
#include <graphics/GraphicsDeviceRenderer.h>
#include <TFT_eSPI.h>
#include <SPI.h>
#include <ResistiveTouchScreen.h>

#define TFT_SPRITE_BITS 4
#define SPRITE_PALETTE_SIZE (1 << TFT_SPRITE_BITS)

using namespace tcgfx;

class TftSpriteAndConfig;

class TfteSpiDrawable : public DeviceDrawable {
private:
    TFT_eSPI* tft;
    TftSpriteAndConfig* spriteWithConfig;
    uint16_t spriteHeight;
public:
    TfteSpiDrawable(TFT_eSPI *tft, int maxSpriteHeight);

    DeviceDrawable *getSubDeviceFor(const Coord &where, const Coord& size, const color_t *palette, int paletteSize) override;

    void internalDrawText(const Coord &where, const void *font, int mag, const char *text) override;

    void drawBitmap(const Coord &where, const DrawableIcon *icon, bool selected) override;

    void drawXBitmap(const Coord &where, const Coord &size, const uint8_t *data) override;

    virtual void drawBitmapNbpp(const Coord& where, const uint8_t* data, const Coord& size, int bpp, const color_t* palette);

    void drawBox(const Coord &where, const Coord &size, bool filled) override;

    void drawCircle(const Coord &where, int radius, bool filled) override;

    void drawPolygon(const Coord *points, int numPoints, bool filled) override;

    void drawPixel(uint16_t x, uint16_t y) override;

    void transaction(bool isStarting, bool redrawNeeded) override;

    Coord internalTextExtents(const void *font, int mag, const char *text, int *baseline) override;
    Coord getDisplayDimensions() override { return Coord(tft->width(), tft->height());}
    TFT_eSPI* getTFT() { return tft; }
protected:
    UnicodeFontHandler* createFontHandler() override;
private:
    void fontPtrToNum(const void* font, int mag);
};

class TftSpriteAndConfig : public TfteSpiDrawable {
private:
    TfteSpiDrawable* root;
    TFT_eSprite sprite;
    Coord where;
    Coord currentSize;
    const Coord size;
    uint8_t currentColorsDefined;
public:
    TftSpriteAndConfig(TfteSpiDrawable *root, int width, int height);

    bool initSprite(const Coord& spriteWhere, const Coord& spriteSize, const color_t* palette, int paletteEntries);
    DeviceDrawable *getSubDeviceFor(const Coord &where, const Coord& size, const color_t *palette, int paletteSize) override { return nullptr; }
    void transaction(bool isStarting, bool redrawNeeded) override;
    color_t getUnderlyingColor(color_t col) override;
    void drawBitmapNbpp(const Coord& where, const uint8_t* data, const Coord& size, int bpp, const color_t* palette) override;
    TFT_eSprite& getTftSprite() { return sprite; }
};

#define TC_TFT_ESPI_NEEDS_TOUCH false
#if TC_TFT_ESPI_NEEDS_TOUCH == true

#define XPT_2046_MAX 4096

namespace iotouch {

    /**
     * Implements the touch interrogator class, this purely gets the current reading from the device when requested. This
     * implementation works with the TFT_eSPI touch functions providing tcMenu support for it. It is your responsibility
     * to have run whatever calibration is needed before calling this function.  The X and Y values to the constructor
     * are the maximum values that can be returned by calling getTouch.
     */
    class TftSpiTouchInterrogator : public iotouch::TouchInterrogator {
    private:
        TFT_eSPI* tft;
        float maxWidthDim;
        float maxHeightDim;
        bool usingRawTouch;
    public:
        TftSpiTouchInterrogator(TFT_eSPI* tft, uint16_t xMax, uint16_t yMax, bool rawTouch)
                : tft(tft), maxWidthDim(xMax), maxHeightDim(yMax), usingRawTouch(rawTouch) { }

        iotouch::TouchState internalProcessTouch(float *ptrX, float *ptrY, const TouchOrientationSettings& touchOrientationSettings,
                                                 const iotouch::CalibrationHandler& calib) override;
    };

}
#endif // TC_TFT_ESPI_NEEDS_TOUCH == true

#endif //TCMENU_PLUGIN_TCMENUTFTESPI_H


// PLUGIN FILE - EthernetTransport.h
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * @file EthernetTransport.h
 * 
 * Ethernet remote capability plugin. This file is a plugin file and should not be directly edited,
 * it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 */

#ifndef TCMENU_ETHERNETTRANSPORT_H_
#define TCMENU_ETHERNETTRANSPORT_H_

#include <RemoteConnector.h>
#include <TaskManager.h>
#include <WiFi.h>
#include <tcUtil.h>
#include <remote/BaseRemoteComponents.h>

#ifndef ETHERNET_BUFFER_SIZE
#define ETHERNET_BUFFER_SIZE 96
#endif

#if ETHERNET_BUFFER_SIZE > 0
#include <remote/BaseBufferedRemoteTransport.h>
#endif

namespace tcremote {

#if ETHERNET_BUFFER_SIZE > 0

/**
 * An implementation of TagValueTransport that is able to read and write via a buffer to sockets.
 */
    class EthernetTagValTransport : public tcremote::BaseBufferedRemoteTransport {
    private:
        WiFiClient client;
    public:
        EthernetTagValTransport() : BaseBufferedRemoteTransport(BUFFER_MESSAGES_TILL_FULL, ETHERNET_BUFFER_SIZE, MAX_VALUE_LEN) { }
        ~EthernetTagValTransport() override = default;
        void setClient(WiFiClient cl) { this->client = cl; }

        int fillReadBuffer(uint8_t* data, int maxSize) override;
        void flush() override;
        bool available() override;
        bool connected() override;
        void close() override;
    };

#else // ethernet buffering not needed

/**
 * An implementation of TagValueTransport that is able to read and write using sockets.
 */
class EthernetTagValTransport : public TagValueTransport {
private:
	WiFiClient client;
public:
	EthernetTagValTransport() : TagValueTransport(TagValueTransportType::TVAL_UNBUFFERED) {};
	~EthernetTagValTransport() override = default;
	void setClient(WiFiClient client) { this->client = client; }

	int writeChar(char data) override ;
	int writeStr(const char* data) override;
	void flush() override;
	bool available() override;
	bool connected() override;
	uint8_t readByte() override;
	bool readAvailable() override;
    void close() override;
};

#endif // ethernet buffering check

/**
 * This class provides the initialisation and connection generation logic for ethernet connections.
 */
class EthernetInitialisation : public DeviceInitialisation {
private:
	WiFiServer *server;
public:
    explicit EthernetInitialisation(WiFiServer* server) : server(server) {}

    bool attemptInitialisation() override;

    bool attemptNewConnection(BaseRemoteServerConnection *transport) override;
};

/**
 * This function converts from a RSSI (Radio Strength indicator)
 * measurement into a series of icons (of the ones we have defined
 * in the stock icons. The input is the RSSI figure in dB as an
 * integer.
 * @param strength the signal strength (usually negative) as an int
 * @return a state that can be used with the standard wifi TitleWidget
 */
int fromWiFiRSSITo4StateIndicator(int strength);

} // namespace tcremote

#ifndef TC_MANUAL_NAMESPACING
using namespace tcremote;
#endif // TC_MANUAL_NAMESPACING

#endif /* TCMENU_ETHERNETTRANSPORT_H_ */

#include <Arduino.h>
#include <tcMenu.h>

#include <tcMenuBuilder.h>
#include <graphics/MenuTouchScreenEncoder.h>
#include <extras/DrawableTouchCalibrator.h>
#include <RemoteConnector.h>
#include <ScrollChoiceMenuItem.h>
#include <RemoteMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <ArduinoEEPROMAbstraction.h>
#include <RemoteAuthentication.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern TFT_eSPI tft;
extern TfteSpiDrawable tftDrawable;
extern GraphicsDeviceRenderer renderer;
extern iotouch::ResistiveTouchInterrogator touchInterrogator;
extern MenuTouchScreenManager touchScreen;
extern tcextras::IoaTouchScreenCalibrator touchCalibrator;
extern WiFiServer server;
extern EthernetInitialisation ethernetInitialisation;

// Any externals needed by IO expanders, EEPROMs etc


// Forward define the menu builder function
void buildMenu(TcMenuBuilder& builder);

// The following defines all menu item IDs.
#define MENU_VOLUME_ID  1
#define MENU_CHANNELS_ID  2
#define MENU_DIRECT_ID  3
#define MENU_MUTE_ID  4
#define MENU_SETTINGS_ID  5
#define MENU_CHANNEL_SETTINGS_ID  7
#define MENU_CHANNEL_SETTINGS_CHANNEL_ID  23
#define MENU_CHANNEL_SETTINGS_LEVEL_TRIM_ID  8
#define MENU_CHANNEL_SETTINGS_NAME_ID  22
#define MENU_CHANNEL_SETTINGS_UPDATE_SETTINGS_ID  24
#define MENU_SETTINGS_WARM_UP_TIME_ID  11
#define MENU_SETTINGS_VALVE_HEATING_ID  17
#define MENU_SAVE_SETTINGS_ID  25
#define MENU_STATUS_ID  6
#define MENU_AMP_STATUS_ID  14
#define MENU_STATUS_LEFT_V_U_ID  15
#define MENU_RIGHT_V_U_ID  16
#define MENU_SHOW_DIALOGS_ID  20
#define MENU_STATUS_DATA_LIST_ID  21
#define MENU_STATUS_TEST_ID  28
#define MENU_CONNECTIVITY_ID  12
#define MENU_I_P_ADDRESS_ID  13
#define MENU_SSID_ID  18
#define MENU_PASSCODE_ID  19
#define MENU_CONNECTIVITY_IO_T_MONITOR_ID  26
#define MENU_CONNECTIVITY_AUTHENTICATOR_ID  27

// Inline helper methods to access menu items
inline AnalogMenuItem& getMenuVolume() { return getAnalogItemById(MENU_VOLUME_ID); }
inline ScrollChoiceMenuItem& getMenuChannel() { return getScrollChoiceItemById(MENU_CHANNELS_ID); }
inline BooleanMenuItem& getMenuDirect() { return getBooleanItemById(MENU_DIRECT_ID); }
inline BooleanMenuItem& getMenuMute() { return getBooleanItemById(MENU_MUTE_ID); }
inline SubMenuItem& getMenuSettings() { return getSubMenuById(MENU_SETTINGS_ID); }
inline SubMenuItem& getMenuChannelSettings() { return getSubMenuById(MENU_CHANNEL_SETTINGS_ID); }
inline ScrollChoiceMenuItem& getMenuChannelNum() { return getScrollChoiceItemById(MENU_CHANNEL_SETTINGS_CHANNEL_ID); }
inline AnalogMenuItem& getMenuLevelTrim() { return getAnalogItemById(MENU_CHANNEL_SETTINGS_LEVEL_TRIM_ID); }
inline TextMenuItem& getMenuName() { return getTextItemById(MENU_CHANNEL_SETTINGS_NAME_ID); }
inline ActionMenuItem& getMenuUpdateSettings() { return getActionItemById(MENU_CHANNEL_SETTINGS_UPDATE_SETTINGS_ID); }
inline AnalogMenuItem& getMenuWarmUpTime() { return getAnalogItemById(MENU_SETTINGS_WARM_UP_TIME_ID); }
inline AnalogMenuItem& getMenuValveHeating() { return getAnalogItemById(MENU_SETTINGS_VALVE_HEATING_ID); }
inline ActionMenuItem& getMenuSaveSettings() { return getActionItemById(MENU_SAVE_SETTINGS_ID); }
inline SubMenuItem& getMenuStatus() { return getSubMenuById(MENU_STATUS_ID); }
inline EnumMenuItem& getMenuAmpStatus() { return getEnumItemById(MENU_AMP_STATUS_ID); }
inline AnalogMenuItem& getMenuLeftVU() { return getAnalogItemById(MENU_STATUS_LEFT_V_U_ID); }
inline AnalogMenuItem& getMenuRightVU() { return getAnalogItemById(MENU_RIGHT_V_U_ID); }
inline ActionMenuItem& getMenuShowDialogs() { return getActionItemById(MENU_SHOW_DIALOGS_ID); }
inline ListRuntimeMenuItem& getMenuDataList() { return getListItemById(MENU_STATUS_DATA_LIST_ID); }
inline AnalogMenuItem& getMenuTest() { return getAnalogItemById(MENU_STATUS_TEST_ID); }
inline SubMenuItem& getMenuConnectivity() { return getSubMenuById(MENU_CONNECTIVITY_ID); }
inline IpAddressMenuItem& getMenuIPAddress() { return getIpAddressItemById(MENU_I_P_ADDRESS_ID); }
inline TextMenuItem& getMenuSSID() { return getTextItemById(MENU_SSID_ID); }
inline TextMenuItem& getMenuPasscode() { return getTextItemById(MENU_PASSCODE_ID); }
inline RemoteMenuItem& getMenuIoTMonitor() { return getIoTRemoteMenuById(MENU_CONNECTIVITY_IO_T_MONITOR_ID); }
inline EepromAuthenticationInfoMenuItem& getMenuAuthenticator() { return getAuthenticationMenuById(MENU_CONNECTIVITY_AUTHENTICATOR_ID); }


// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return getMenuVolume(); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnChannelSettingsChannelRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
int fnStatusDataListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onAudioDirect(int id);
void CALLBACK_FUNCTION onChannelChanged(int id);
void CALLBACK_FUNCTION onChannelSetttingsUpdate(int id);
void CALLBACK_FUNCTION onMuteSound(int id);
void CALLBACK_FUNCTION onSaveSettings(int id);
void CALLBACK_FUNCTION onShowDialogs(int id);
void CALLBACK_FUNCTION onVolumeChanged(int id);
void CALLBACK_FUNCTION valveHeatingChanged(int id);
void CALLBACK_FUNCTION warmUpChanged(int id);

#endif // MENU_GENERATED_CODE_H
