/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "ledFlashNoRemote_menu.h"

// Global variable declarations

LiquidCrystal lcd(LCD_RS, LCD_EN, LCD_D4, LCD_D5, LCD_D6, LCD_D7);
LiquidCrystalRenderer renderer(lcd, LCD_WIDTH, LCD_HEIGHT);

// Global Menu Item declarations

const PROGMEM AnyMenuInfo minfoSaveLEDState = { "Save LED state", 3, 0xffff, 0, onSaveState };
ActionMenuItem menuSaveLEDState(&minfoSaveLEDState, NULL);
const PROGMEM AnalogMenuInfo minfoA0Volts = { "A0Volts", 2, 0xffff, 1024, NO_CALLBACK, 0, 200, "V" };
AnalogMenuItem menuA0Volts(&minfoA0Volts, 0, &menuSaveLEDState);
const PROGMEM BooleanMenuInfo minfoBuiltInLED = { "BuiltIn LED", 1, 2, 1, onLedChange, NAMING_ON_OFF };
BooleanMenuItem menuBuiltInLED(&minfoBuiltInLED, false, &menuA0Volts);
const PROGMEM ConnectorLocalInfo applicationInfo = { "LED Blink", "86bb814a-5b77-45eb-8050-7dba18617635" };

// Set up code

void setupMenu() {
    lcd.setIoAbstraction(ioUsingArduino());
    lcd.begin(LCD_WIDTH, LCD_HEIGHT);
    lcd.configureBacklightPin(LCD_BACKLIGHT);
    lcd.backlight();
    switches.initialise(ioUsingArduino(), true);
    menuMgr.initForEncoder(&renderer, &menuBuiltInLED, ENCODER_PIN_A, ENCODER_PIN_B, ENCODER_PIN_OK);
}

