/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <GxEPD2_BW.h>
#include <TcMenuGxEPDeInk.h>
#include "EthernetTransport.h"
#include <RemoteConnector.h>
#include <tcUnicodeHelper.h>
#include <RemoteMenuItem.h>
#include <RuntimeMenuItem.h>
#include <ScrollChoiceMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <esp32/EspPreferencesEeprom.h>
#include <RemoteAuthentication.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern TcGxEPD2 display;
extern GraphicsDeviceRenderer renderer;
extern WiFiServer server;
extern EthernetInitialisation ethernetInitialisation;

// Any externals needed by IO expanders, EEPROMs etc
extern EspPreferencesEeprom glEspRom;

#define HIBERNATE_ID 21
#define INT_EDIT_ID 1
#define DEC_EDIT_ID 2
#define HALVES_ID 3
#define FOODS_ID 4
#define DOOR_OPEN_ID 5
#define EXTRAS_ID 6
#define EXTRAS_TEXT_ID 11
#define EXTRAS_RGB_ID 12
#define EXTRAS_LIST_ID 13
#define CONNECTIVITY_ID 14
#define CONNECTIVITY_SSID_ID 15
#define CONNECTIVITY_PASSCODE_ID 16
#define CONNECTIVITY_WIFI_MODE_ID 17
#define CONNECTIVITY_IP_ADDR_ID 18
#define CONNECTIVITY_MON_ID 19
#define CONNECTIVITY_AUTH_ID 20

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return *getMenuItemById(HIBERNATE_ID); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onListSelected(int id);
int fnExtrasMyListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onHibernate(int id);

#endif // MENU_GENERATED_CODE_H
