/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino ESP32 by TcMenu 4.5.0 on 2026-01-18T09:39:52.216322Z.

#include <tcMenu.h>
#include "esp32s2Saola_menu.h"
#include "einkThemeBuilderBlock.h"
#include "TcMenuBuilder.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "ESP32-S2 Saola board", "b447b433-fe4f-4ce7-8746-d94bfeefc707" };
TcMenuRemoteServer remoteServer(applicationInfo);
EspPreferencesEeprom glEspRom("menuStore", 512);
EepromAuthenticatorManager authManager(4);
TcGxEPD2 display(GxEPD2_154_GDEY0154D67(13, 14, 15, 16));
AdafruitDrawable displayDrawable(&display);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &displayDrawable);
WiFiServer server(3333);
EthernetInitialisation ethernetInitialisation(&server);
EthernetTagValTransport ethernetTransport;
TagValueRemoteServerConnection ethernetConnection(ethernetTransport, ethernetInitialisation);

const char* enumWiFiMode[] = { "Station", "Soft AP" };
const char* enumFoodsArray[] = { "Pizza", "Pasta", "Salad", "Pie" };

void buildMenu(TcMenuBuilder& builder) {
    builder.usingDynamicEEPROMStorage()
        .actionItem(HIBERNATE_ID, "Hibernate", NoMenuFlags, onHibernate)
        .analogBuilder(INT_EDIT_ID, "Int Edit", ROM_SAVE, NoMenuFlags, 4)
            .offset(0).divisor(1).maxValue(100).unit("%").endItem()
        .analogBuilder(DEC_EDIT_ID, "Dec Edit", ROM_SAVE, NoMenuFlags, 0)
            .offset(0).divisor(100).maxValue(1000).unit("oC").endItem()
        .analogBuilder(HALVES_ID, "Halves", ROM_SAVE, MenuFlags().readOnly(), 0)
            .offset(0).divisor(2).maxValue(100).unit("").endItem()
        .enumItem(FOODS_ID, "Foods", ROM_SAVE, enumFoodsArray, 4, NoMenuFlags)
        .boolItem(DOOR_OPEN_ID, "Door Open", ROM_SAVE, NAMING_YES_NO, NoMenuFlags)
        .subMenu(EXTRAS_ID, "Extras", NoMenuFlags)
            .textItem(EXTRAS_TEXT_ID, "Text", ROM_SAVE, 10, NoMenuFlags)
            .rgb32Item(EXTRAS_RGB_ID, "Color", ROM_SAVE, false, NoMenuFlags)
            .listItemRtCustom(EXTRAS_LIST_ID, "My List", 10, fnExtrasMyListRtCall, NoMenuFlags)
            .endSub()
        .subMenu(CONNECTIVITY_ID, "Connectivity", NoMenuFlags)
            .textItem(CONNECTIVITY_SSID_ID, "SSID", ROM_SAVE, 20, NoMenuFlags)
            .textItem(CONNECTIVITY_PASSCODE_ID, "Passcode", ROM_SAVE, 20, NoMenuFlags)
            .enumItem(CONNECTIVITY_WIFI_MODE_ID, "WiFi Mode", ROM_SAVE, enumWiFiMode, 2, NoMenuFlags)
            .ipAddressItem(CONNECTIVITY_IP_ADDR_ID, "IP Address", DONT_SAVE, NoMenuFlags)
            .remoteConnectivityMonitor(CONNECTIVITY_MON_ID, "IoT Monitor", MenuFlags().localOnly())
            .eepromAuthenticationItem(CONNECTIVITY_AUTH_ID, "Authenticator", MenuFlags().localOnly())
            .endSub();
}

void setupMenu() {
    auto builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    glEspRom.init();
    menuMgr.setEepromRef(&glEspRom);
    authManager.initialise(menuMgr.getEepromAbstraction(), 200);
    menuMgr.setAuthenticator(&authManager);

    // Code generated by plugins and new operators.
    display.init(115200, true, 10, false);
    display.setRotation(0);
    renderer.setUpdatesPerSecond(1);
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, true);
    menuMgr.initFor4WayJoystick(&renderer, builder.getRootItem(), 2, 1, 3, 4, -1, 20);
    remoteServer.addConnection(&ethernetConnection);
    applyTheme(renderer);

    // We have an IoT monitor, register the server
    getIoTRemoteMenuById(CONNECTIVITY_MON_ID).setRemoteServer(remoteServer);

    // We have an EEPROM authenticator, it needs initialising
    getAuthenticationMenuById(CONNECTIVITY_AUTH_ID).init();
}

