/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>

#include "tcMenuU8g2.h"
#include <RuntimeMenuItem.h>
#include <EditableLargeNumberMenuItem.h>

// all variables that need exporting
extern U8G2_SH1106_128X64_NONAME_F_SW_I2C gfx;
extern GraphicsDeviceRenderer renderer;

// all menu item forward references.
extern ActionMenuItem menuSettingsSaveSettings;
extern EditableLargeNumberMenuItem menuSettingsSerialNumber;
extern TextMenuItem menuSettingsUserName;
extern BooleanMenuItem menuSettingsSafetyLock;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern ActionMenuItem menuStartToasting;
extern BooleanMenuItem menuFrozen;
extern EnumMenuItem menuType;
extern AnalogMenuItem menuToasterPower;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onNameChanged(int id);
void CALLBACK_FUNCTION onSaveSettings(int id);
void CALLBACK_FUNCTION onStartToasting(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
