/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "adafruitST7735Mega_menu.h"
#include "ThemeCoolBlueTraditional.h"
#include <Fonts/OpenSansCyrillicLatin12.h>

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "adaAvrTest", "0b2b11cf-0567-4173-9fbc-80d56674cbb3" };
IoAbstractionRef ioexp_mcp23017 = ioFrom23017(0x20, ACTIVE_LOW_OPEN, 2);
Adafruit_ST7735 gfx(6, 7, -1);
AdafruitDrawable gfxDrawable(&gfx, 20);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);

// Global Menu Item declarations
const PROGMEM FloatMenuInfo minfoFlt = { "Flt", 6, 0xffff, 3, NO_CALLBACK };
FloatMenuItem menuFlt(&minfoFlt, 0.0, NULL, INFO_LOCATION_PGM);
const PROGMEM AnyMenuInfo minfoSubPressMe = { "Press me", 5, 0xffff, 0, NO_CALLBACK };
ActionMenuItem menuSubPressMe(&minfoSubPressMe, &menuFlt, INFO_LOCATION_PGM);
const PROGMEM SubMenuInfo minfoSub = { "Sub", 4, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSub(&minfoSub, &menuSubPressMe, INFO_LOCATION_PGM);
SubMenuItem menuSub(&minfoSub, &menuBackSub, NULL, INFO_LOCATION_PGM);
RENDERING_CALLBACK_NAME_INVOKE(fnLgeRtCall, largeNumItemRenderFn, "Lge", -1, NO_CALLBACK)
EditableLargeNumberMenuItem menuLge(fnLgeRtCall, LargeFixedNumber(5, 2, 0U, 0U, false), 3, true, &menuSub);
const PROGMEM BooleanMenuInfo minfoBool = { "Bool", 2, 0xffff, 1, NO_CALLBACK, NAMING_YES_NO };
BooleanMenuItem menuBool(&minfoBool, false, &menuLge, INFO_LOCATION_PGM);
const PROGMEM AnalogMenuInfo minfoAnalog = { "Analog", 1, 0xffff, 255, NO_CALLBACK, 0, 1, "Unit" };
AnalogMenuItem menuAnalog(&minfoAnalog, 0, &menuBool, INFO_LOCATION_PGM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    // Code generated by plugins.
    gfx.initR(INITR_BLACKTAB);
    gfx.setRotation(3);
    renderer.setUpdatesPerSecond(4);
    switches.init(ioexp_mcp23017, SWITCHES_NO_POLLING, true);
    menuMgr.initForEncoder(&renderer, &menuAnalog, 6, 7, 5);
    renderer.setTitleMode(BaseGraphicalRenderer::TITLE_FIRST_ROW);
    renderer.setUseSliderForAnalog(true);
    renderer.enableTcUnicode();
    installCoolBlueTraditionalTheme(renderer, MenuFontDef(&OpenSansCyrillicLatin12, 0), MenuFontDef(&OpenSansCyrillicLatin12, 0), true);
}

