/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include "Adafruit_GFX.h"
#include "Adafruit_ST7735.h"
#include "tcMenuAdaFruitGfx.h"
#include "EthernetTransport.h"
#include <RemoteConnector.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern Adafruit_ST7735 gfx;
extern AdaColorGfxMenuConfig colorConfig;
extern AdaFruitGfxMenuRenderer renderer;
extern IoAbstractionRef io8574;
extern EthernetServer server;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

extern IpAddressMenuItem menuIpAddress;
extern SubMenuItem menuConnectivity;
extern FloatMenuItem menuVoltA1;
extern FloatMenuItem menuVoltA0;
extern SubMenuItem menuStatus;
extern BooleanMenuItem menuTempCheck;
extern ActionMenuItem menuHiddenItem;
extern BooleanMenuItem menuSCircuitProtect;
extern SubMenuItem menuAdvanced;
void CALLBACK_FUNCTION onSaveRom(int id);
extern ActionMenuItem menuSaveAll;
extern BooleanMenuItem menuPwrDelay;
extern SubMenuItem menuSettings;
void CALLBACK_FUNCTION onLimitMode(int id);
extern EnumMenuItem menuLimit;
void CALLBACK_FUNCTION onCurrentChange(int id);
extern AnalogMenuItem menuCurrent;
void CALLBACK_FUNCTION onVoltageChange(int id);
extern AnalogMenuItem menuVoltage;

#endif // MENU_GENERATED_CODE_H
