/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>

#include "tcMenuAdaFruitGfx.h"
#include <Fonts/FreeSans9pt7b.h>
#include "EthernetTransport.h"
#include <RemoteConnector.h>
#include <RuntimeMenuItem.h>
#include <ScrollChoiceMenuItem.h>

// all define statements needed
#define DISPLAY_VARIABLE gfx
#define DISPLAY_TYPE Adafruit_ST7735
#define DISPLAY_CONFIG 
#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 128
#define DISPLAY_RESET_PIN 3
#define DISPLAY_CS_PIN 6
#define DISPLAY_RS_PIN 7
#define DISPLAY_DATA_PIN -1
#define DISPLAY_CLOCK_PIN -1
#define DISPLAY_ROTATION 1
#define DISPLAY_TITLE_FONT FreeSans9pt7b
#define DISPLAY_ITEM_FONT NULL
#define UPDATES_PER_SEC 5
#define PULLUP_LOGIC true
#define INTERRUPT_SWITCHES true
#define SWITCH_IODEVICE io8574
#define ENCODER_PIN_A 7
#define ENCODER_PIN_B 6
#define ENCODER_PIN_OK 5
#define LIBRARY_TYPE ETHERNET_2
#define LISTEN_PORT 3333

// all variables that need exporting
extern Adafruit_ST7735 gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern IoAbstractionRef io8574;
extern EthernetServer server;

// all menu item forward references.
extern ActionMenuItem menuTakeDisplay;
extern ActionMenuItem menuSaveItem;
extern TextMenuItem menuRomText;
extern ScrollChoiceMenuItem menuRomLocation;
extern ScrollChoiceMenuItem menuRomChoice;
extern BackMenuItem menuBackRomValues;
extern SubMenuItem menuRomValues;
extern IpAddressMenuItem menuIpAddress;
extern BackMenuItem menuBackConnectivity;
extern SubMenuItem menuConnectivity;
extern FloatMenuItem menuVoltA1;
extern FloatMenuItem menuVoltA0;
extern BackMenuItem menuBackStatus;
extern SubMenuItem menuStatus;
extern Rgb32MenuItem menuRGB;
extern BooleanMenuItem menuTempCheck;
extern ActionMenuItem menuHiddenItem;
extern BooleanMenuItem menuSCircuitProtect;
extern BackMenuItem menuBackAdvanced;
extern SubMenuItem menuAdvanced;
extern ActionMenuItem menuSaveAll;
extern BooleanMenuItem menuPwrDelay;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern EnumMenuItem menuLimit;
extern AnalogMenuItem menuCurrent;
extern AnalogMenuItem menuVoltage;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

int fnRomLocationRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);
void CALLBACK_FUNCTION onCurrentChange(int id);
void CALLBACK_FUNCTION onLimitMode(int id);
void CALLBACK_FUNCTION onRgbChanged(int id);
void CALLBACK_FUNCTION onSaveItem(int id);
void CALLBACK_FUNCTION onSaveRom(int id);
void CALLBACK_FUNCTION onTakeDisplay(int id);
void CALLBACK_FUNCTION onVoltageChange(int id);

void setupMenu();

#endif // MENU_GENERATED_CODE_H
