/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>

#include "tcMenuU8g2.h"
#include "SimhubConnector.h"

// all define statements needed
#define DISPLAY_VARIABLE gfx
#define DISPLAY_TYPE U8G2_SH1106_128X64_NONAME_F_SW_I2C
#define DISPLAY_CONFIG 
#define SERIAL_PORT Serial
#define STATUS_MENUITEM 3

// all variables that need exporting
extern U8G2_SH1106_128X64_NONAME_F_SW_I2C gfx;
extern U8g2GfxMenuConfig gfxConfig;
extern U8g2MenuRenderer renderer;

// all menu item forward references.
extern BooleanMenuItem menuSimHubLink;
extern AnalogMenuItem menuRPM;
extern AnalogMenuItem menuSpeed;
extern const ConnectorLocalInfo applicationInfo;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION


void setupMenu();

#endif // MENU_GENERATED_CODE_H
