/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include "tcMenuAdaFruitGfx.h"
#include "ESP32TouchKeysAbstraction.h"
#include "SimhubConnector.h"
#include <RuntimeMenuItem.h>
#include <EditableLargeNumberMenuItem.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // contains app name and ID

// Global variables that need exporting

extern Adafruit_ILI9341 gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern ESP32TouchKeysAbstraction esp32Touch;
extern const GFXfont FreeSans9pt7b;
extern const GFXfont FreeSans12pt7b;

// Global Menu Item exports

extern ActionMenuItem menuShowDashboard;
extern AnalogMenuItem menuLap;
extern EnumMenuItem menuDashboard;
extern EditableLargeNumberMenuItem menuSettingsLargeTest;
extern BooleanMenuItem menuSettingsOverboost;
extern ActionMenuItem menuSettingsShowDialogs;
extern AnalogMenuItem menuSettingsTestItem1;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern BooleanMenuItem menuSimHubLink;
extern AnalogMenuItem menuTyreTemp;
extern TextMenuItem menuGear;
extern AnalogMenuItem menuRPM;
extern AnalogMenuItem menuSpeed;

// Provide a wrapper to get hold of the root menu item
inline MenuItem& rootMenuItem() { return menuSpeed; }

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onConnectionChange(int id);
void CALLBACK_FUNCTION onDashChanged(int id);
void CALLBACK_FUNCTION onShowDash(int id);
void CALLBACK_FUNCTION onShowDialogs(int id);

#endif // MENU_GENERATED_CODE_H
