#include "ESP32S2EInk_menu.h"
#include <TaskManagerIO.h>
#include <EEPROM.h>
#include <tcMenuVersion.h>
#include <WiFi.h>
#include <stockIcons/wifiAndConnectionIcons16x12.h>
#include <tcUtil.h>
#include <SPI.h>
#include <BaseDialog.h>

#include "graphics/TcThemeBuilder.h"

#define MENU_WIFIMODE_STATION 0
bool  connectedToWiFi = false;
void startWiFiAndListener();

// we add two widgets, one generated by tcMenu Designer Bitmap and Widget Creator, and the inbuilt Wi-Fi widget
// START widgets

// https://www.thecoderscorner.com/products/arduino-libraries//tc-menu/rendering-with-tcmenu-lcd-tft-oled
TitleWidget wifiWidget(iconsWifi, 5, 16, 12);

using namespace tcgfx;

// XBM_LSB_FIRST width=12, height=12, size=24
// auto size = Coord(12, 12);
const uint8_t myWidgetWidIcon0[] PROGMEM = {
    0x00,0x00,0x8e,0x03,0x51,0x04,0x51,0x04,0x51,0x04,0x51,0x04,0x51,0x04,0x51,0x04,0x59,0x06,0x5d,0x07,
    0x5d,0x07,0x8e,0x03
    };
// XBM_LSB_FIRST width=12, height=12, size=24
// auto size = Coord(12, 12);
const uint8_t myWidgetWidIcon1[] PROGMEM = {
    0x00,0x00,0x8e,0x03,0xd7,0x05,0xd7,0x05,0xd3,0x04,0x51,0x04,0x51,0x04,0x51,0x04,0x51,0x04,0x51,0x04,
    0x51,0x04,0x8e,0x03
    };
const uint8_t* const myWidgetWidIcons[] PROGMEM = { myWidgetWidIcon0, myWidgetWidIcon1 };

// See https://www.thecoderscorner.com/products/arduino-libraries//tc-menu/creating-and-using-bitmaps-menu/
TitleWidget myWidgetWidget(myWidgetWidIcons, 2, 12, 12, nullptr);

// END widgets

// Declaring any arrays used by enum/list items
const char* FoodsEnumEntries[] = { "Pizza", "Pasta", "Salad", "Pie" };
const char* ConnectivityWiFiModeEnumEntries[] = { "Station", "Soft AP" };

void buildMenu(TcMenuBuilder& builder) {
    builder        .actionItem(MENU_HIBERNATE_ID, "Hibernate", NoMenuFlags, onHibernate)
        .analogBuilder(MENU_INT_EDIT_ID, "Int Edit", 2, NoMenuFlags, 0, nullptr)
            .offset(0).divisor(1).step(1).maxValue(100).unit("%").endItem()
        .analogBuilder(MENU_DEC_EDIT_ID, "Dec Edit", 4, NoMenuFlags, 0, nullptr)
            .offset(0).divisor(10).step(1).maxValue(1000).unit("oC").endItem()
        .analogBuilder(MENU_HALVES_ID, "Halves", 6, NoMenuFlags, 0, nullptr)
            .offset(0).divisor(2).step(1).maxValue(200).unit("").endItem()
        .enumItem(MENU_FOODS_ID, "Foods", 8, FoodsEnumEntries, 4, NoMenuFlags, 0, nullptr)
        .boolItem(MENU_DOOR_OPEN_ID, "Door Open", 10, NAMING_YES_NO, NoMenuFlags, false, nullptr)
        .subMenu(MENU_EXTRAS_ID, "Extras", NoMenuFlags, nullptr)
            .textItem(MENU_EXTRAS_TEXT_ID, "Text", 11, 5, NoMenuFlags, "", nullptr)
            .rgb32Item(MENU_EXTRAS_COLOR_ID, "Color", 16, false, NoMenuFlags, RgbColor32(0, 0, 0), nullptr)
            .listItemRtCustom(MENU_EXTRAS_MY_LIST_ID, "My List", 0, fnExtrasMyListRtCall, NoMenuFlags, onListSelected)
            .endSub()
        .subMenu(MENU_CONNECTIVITY_ID, "Connectivity", NoMenuFlags, nullptr)
            .textItem(MENU_CONNECTIVITY_S_S_I_D_ID, "SSID", 20, 22, NoMenuFlags, "", nullptr)
            .textItem(MENU_CONNECTIVITY_PASSCODE_ID, "Passcode", 42, 22, NoMenuFlags, "", nullptr)
            .enumItem(MENU_CONNECTIVITY_WI_FI_MODE_ID, "WiFi Mode", 64, ConnectivityWiFiModeEnumEntries, 2, NoMenuFlags, 0, nullptr)
            .ipAddressItem(MENU_CONNECTIVITY_I_P_ADDRESS_ID, "IP Address", DONT_SAVE, NoMenuFlags, IpAddressStorage(127, 0, 0, 1), nullptr)
            .remoteConnectivityMonitor(MENU_CONNECTIVITY_IO_T_MONITOR_ID, "IoT Monitor", MenuFlags().localOnly())
            .eepromAuthenticationItem(MENU_CONNECTIVITY_AUTHENTICATOR_ID, "Authenticator", MenuFlags().localOnly(), nullptr)
            .endSub()
        .subMenu(MENU_IO_T_SETUP_ID, "IoT Setup", NoMenuFlags, nullptr)
            .ipAddressItem(MENU_I_P_ADDR_ID, "IP Addr", DONT_SAVE, NoMenuFlags, IpAddressStorage(127, 0, 0, 1), nullptr)
            .remoteConnectivityMonitor(MENU_IO_T_MONITOR1_ID, "IoT Monitor1", MenuFlags().localOnly())
            .endSub();
}



void setup() {
    // before proceeding, we must start wire and serial, then call setup menu.
    Serial.begin(115200);
    serdebugF("Starting ESP32-S2 example");
    SPI.begin(36, 37, 35, -1);

    setupMenu();

    // always call load after setupMenu, as the EEPROM you chose in initialised only after this setupMenu()
    menuMgr.load();

    // set the number of rows in the list.
    getMenuMyList().setNumberOfRows(42);

    // next start WiFi and register our wifi widget
    startWiFiAndListener();

    auto themeBuilder = TcThemeBuilder(renderer);
    themeBuilder.addingTitleWidget(wifiWidget);
    themeBuilder.addingTitleWidget(myWidgetWidget);

    // lastly we capture when the root title is pressed present a standard version dialog.
    setTitlePressedCallback([](int titleCb) {
        showVersionDialog(&applicationInfo);
    });
}

void loop() {
    taskManager.runLoop();

}

// This callback needs to be implemented by you, see the below docs:
//  1. List Docs - https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/menu-item-types/list-menu-item/
//  2. ScrollChoice Docs - https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/menu-item-types/scrollchoice-menu-item/
int CALLBACK_FUNCTION fnExtrasMyListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize) {
    switch(mode) {
    default:
        return defaultRtListCallback(item, row, mode, buffer, bufferSize);
    }
}

void CALLBACK_FUNCTION onListSelected(int id) {
    Serial.print("List item select "); Serial.println(getMenuMyList().getActiveIndex());

}

void CALLBACK_FUNCTION onHibernate(int id) {
    display.clearScreen();
    display.hibernate();
}

void saveToRom() {
    menuMgr.save();
    EEPROM.commit();
    auto dlg = renderer.getDialog();
    if(!dlg->isInUse()) {
        dlg->setButtons(BTNTYPE_NONE, BTNTYPE_CLOSE);
        dlg->showRam("Saved", false);
        dlg->copyIntoBuffer("to flash");
    }
}

void startWiFiAndListener() {
    TextMenuItem& ssidMenuItem = getMenuSSID();
    TextMenuItem& passphraseMenuItem = getMenuPasscode();
    // You can choose between station and access point mode by setting the connectivity/Wifi Mode option to your
    // own choice
    if(getMenuWiFiMode().getCurrentValue() == MENU_WIFIMODE_STATION) {
        // we are in station mode
        WiFi.begin(ssidMenuItem.getTextValue(), passphraseMenuItem.getTextValue());
        WiFi.mode(WIFI_STA);
        serdebugF("Connecting to Wifi using settings from connectivity menu");
    }
    else {
        // we are in access point mode
        WiFi.mode(WIFI_AP);
        char ssid[25];
        char pwd[25];
        copyMenuItemValueDefault(&ssidMenuItem, ssid, sizeof ssid, "tcmenu");
        copyMenuItemValueDefault(&passphraseMenuItem, pwd, sizeof pwd, "secret");
        WiFi.softAP(ssid, pwd);
        serdebugF3("Started up in AP mode, connect with ", ssid, pwd);
    }

    //
    // Here we use the inbuilt task manager to schedule something to run every second. To use
    // it you simply provide either a function callback or a lambda as we do here.
    //
    taskManager.schedule(repeatSeconds(1), [] {
        // check the wifi connection status
        if(WiFi.status() == WL_CONNECTED) {
            if(!connectedToWiFi) {
                // we are fully connected, so we now get the address that DHCP gave us to put into
                // the Ip Address item.
                IPAddress localIp = WiFi.localIP();
                Serial.print("Now connected to WiFi");
                Serial.println(localIp);
                getMenuIPAddr().setIpAddress(localIp[0], localIp[1], localIp[2], localIp[3]);
                connectedToWiFi = true;
            }

            // if the networking is up, then we always render the current signal strength in the title widget.
            wifiWidget.setCurrentState(fromWiFiRSSITo4StateIndicator(WiFi.RSSI()));
        }
        else {
            // We've not got networking, set it
            connectedToWiFi = false;
            wifiWidget.setCurrentState(0);
        }
    });
}
