/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for STM32Duino by TcMenu 4.5.0 on 2025-11-01T12:40:18.579351300Z.

#include <tcMenu.h>
#include "stm32DuinoOneButton_menu.h"
#include "ThemeMonoInverseBuilder.h"
#include <Fonts/OpenSansRegular8pt.h>

#include "TcMenuBuilder.h"

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "One Button", "4fe6e85d-2bbd-4d19-84e5-5d6746883028" };
TcMenuRemoteServer remoteServer(applicationInfo);
HalStm32EepromAbstraction glBspRom;
U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI gfx(U8G2_R0, PF13, PD15, PF12);
U8g2Drawable gfxDrawable(&gfx);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);
TcOneButtonHandler oneButtonHandler(USER_BTN, 250);
NoInitialisationNeeded serialInitializer;
SerialTagValueTransport serialTransport(&Serial);
TagValueRemoteServerConnection serialConnection(serialTransport, serialInitializer);

const char* enumSettingValues[] = { "Spanner", "Hammer", "Plane" };

void buildMenu(TcMenuBuilder& builder) {
    builder.usingDynamicEEPROMStorage()
        .actionItem(MENU_PRESS_ME_ID, "Press Me", NoMenuFlags, onPressMe)
        .analogBuilder(MENU_TEMP_ID, "Temp", DONT_SAVE, NoMenuFlags)
            .maxValue(100).offset(0).divisor(1).unit("%")\
            .endItem()
        .subMenu(MENU_SETTINGS_ID, "Settings", NoMenuFlags)
            .boolItem(MENU_SETTINGS_OPTION_ID, "Option", DONT_SAVE, NAMING_TRUE_FALSE, NoMenuFlags)
            .enumItem(MENU_SETTINGS_ENUM_ID, "Tooling", DONT_SAVE, enumSettingValues, 3, NoMenuFlags)
            .analogBuilder(MENU_SETTINGS_INT_ID, "IntProp", DONT_SAVE, NoMenuFlags)
                .maxValue(10).offset(0).divisor(1).unit("A").endItem()
            .endSub();
}

void setupMenu() {
    auto builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    glBspRom.initialise(0);
    menuMgr.setEepromRef(&glBspRom);
    // Code generated by plugins and new operators.
    gfx.begin();
    renderer.setUpdatesPerSecond(5);
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, false);
    menuMgr.initWithoutInput(&renderer, getMenuItemById(MENU_PRESS_ME_ID));
    oneButtonHandler.start();
    remoteServer.addConnection(&serialConnection);
    installMonoInverseTitleTheme(renderer, MenuFontDef(&OpenSansRegular8pt, 0), MenuFontDef(&OpenSansRegular8pt, 0), true, BaseGraphicalRenderer::NO_TITLE, true);
}

