/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <tcUnicodeHelper.h>
#include "tcMenuU8g2.h"
#include <extras/TcOneButtonHandler.h>
#include <RemoteConnector.h>
#include "SerialTransport.h"
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <mbed/HalStm32EepromAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern TcMenuRemoteServer remoteServer;
extern U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI gfx;
extern U8g2Drawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern TcOneButtonHandler oneButtonHandler;
extern const UnicodeFont OpenSansRegular8pt[];

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item IDs
#define MENU_PRESS_ME_ID 1
#define MENU_TEMP_ID 2
#define MENU_SETTINGS_ID 3
#define MENU_SETTINGS_OPTION_ID 4
#define MENU_SETTINGS_INT_ID 5
#define MENU_SETTINGS_ENUM_ID 6

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return *getMenuItemById(MENU_PRESS_ME_ID); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onPressMe(int id);

#endif // MENU_GENERATED_CODE_H
