/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <mbed.h>
#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include "Adafruit_SSD1306.h"
#include "tcMenuAdaFruitGfx.h"
#include "MBedEthernetTransport.h"
#include <RemoteConnector.h>
#include <ScrollChoiceMenuItem.h>
#include <EditableLargeNumberMenuItem.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // contains app name and ID

// Global variables that need exporting

extern SPI spi;
extern Adafruit_SSD1306_Spi gfx;
extern AdafruitDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;

// Global Menu Item exports

extern TextMenuItem menuEdit;
extern AnalogMenuItem menuCommits;
extern IpAddressMenuItem menuIP;
extern SubMenuItem menuConnectivity;
extern ActionMenuItem menuSaveAll;
extern FloatMenuItem menuAvgTemp;
int fnCountingListRtCall(RuntimeMenuItem * item, uint8_t row, RenderFnMode mode, char * buffer, int bufferSize);
extern ListRuntimeMenuItem menuCountingList;
extern ScrollChoiceMenuItem menuChoices;
extern SubMenuItem menuOther;
extern Rgb32MenuItem menuRGB;
extern EditableLargeNumberMenuItem menuFrequency;
extern BooleanMenuItem menuPower;
extern EnumMenuItem menuFoods;
extern AnalogMenuItem menuTenths;
extern SubMenuItem menuEditing;
extern TimeFormattedMenuItem menuRTCTime;
extern DateFormattedMenuItem menuRTCDate;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onSaveAll(int id);
void CALLBACK_FUNCTION onFrequencyChanged(int id);
void CALLBACK_FUNCTION onFoodChange(int id);
void CALLBACK_FUNCTION onTenthsChaned(int id);

#endif // MENU_GENERATED_CODE_H
