/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include "Adafruit_GFX.h"
#include "Adafruit_PCD8544.h"
#include "tcMenuAdaFruitGfx.h"
#include "EthernetTransport.h"
#include <RemoteConnector.h>

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern Adafruit_PCD8544 gfx;
extern AdaColorGfxMenuConfig gfxConfig;
extern AdaFruitGfxMenuRenderer renderer;
extern EthernetServer server;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

extern IpAddressMenuItem menuIP;
extern SubMenuItem menuConnectivity;
extern TextMenuItem menuTxt;
extern FloatMenuItem menuCurrent;
extern FloatMenuItem menuVoltsIn;
extern SubMenuItem menuStatus;
void CALLBACK_FUNCTION onPowerDownDetected(int id);
extern ActionMenuItem menuShutdownNow;
extern AnalogMenuItem menuDelay;
extern BooleanMenuItem menuPwrDelay;
extern SubMenuItem menuSettings;
extern EnumMenuItem menuOnAlm;
void CALLBACK_FUNCTION onKitchenLight(int id);
extern AnalogMenuItem menuKitchen;
void CALLBACK_FUNCTION onLivingRoomLight(int id);
extern AnalogMenuItem menuLiving;
void CALLBACK_FUNCTION onHallLight(int id);
extern AnalogMenuItem menuHall;

#endif // MENU_GENERATED_CODE_H
