// TcMenu Generated Locale File, do not edit this file. Locale 
// Never include directly, always include the langSelect header

#define TC_I18N_MENU_2_NAME "Float"
#define TC_I18N_MENU_8_NAME "YesNo"
#define TC_I18N_MENU_5_NAME "Settings"
#define TC_I18N_PROJECT_NAME "Adafruit Dashboard"
#define TC_I18N_MENU_7_NAME "RGB"
#define TC_I18N_MENU_3_ENUM_1 "Item2"
#define TC_I18N_MENU_3_ENUM_2 "ChangeMe"
#define TC_I18N_MENU_1_NAME "Analog"
#define TC_I18N_MENU_4_NAME "Power"
#define TC_I18N_MENU_1_UNIT "V"
#define TC_I18N_MENU_3_ENUM_0 "Item 1"
#define TC_I18N_MENU_6_NAME "Action"
#define TC_I18N_MENU_3_NAME "Enum"
