/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino 32bit ARM by TcMenu 4.5.2 on 2026-04-12T15:13:22.907110374Z.

#include <tcMenu.h>
#include "MkrEthernetOLED_menu.h"

// Each plugin's code now follows here

// PLUGIN FILE - tcMenuU8g2.cpp
/*
 * Copyright (c) 2018 https://www.thecoderscorner.com (Dave Cherry).
 * This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
 */

/**
 * @file tcMenuU8g2.h
 *
 * U8g2 renderer that renders menus onto this type of display. This file is a plugin file and should not
 * be directly edited, it will be replaced each time the project is built. If you want to edit this file in place,
 * make sure to rename it first.
 *
 * LIBRARY REQUIREMENT
 * This library requires the u8g2 library available for download from your IDE library manager.
 */

#include <U8g2lib.h>
#include <Wire.h>

#include <tcUnicodeU8G2.h>

using namespace tcgfx;

const uint8_t* safeGetFont(const void* fnt) {
    if(fnt) return static_cast<const uint8_t *>(fnt);
    return u8g2_font_6x10_tf;
}

#define TC_USE_UTF_8_ENCODING false

#if WANT_TASK_MANAGER_FRIENDLY_YIELD == 1
static uint8_t bytesSent = 0;
TwoWire* U8g2Drawable::pWire = nullptr;
uint8_t u8g2_byte_with_yield(u8x8_t *u8x8, uint8_t msg, uint8_t arg_int, void *arg_ptr) {
    if(!U8g2Drawable::pWire) return 0;
    switch(msg)
    {
        case U8X8_MSG_BYTE_SEND:
            bytesSent+= arg_int;
            U8g2Drawable::pWire->write((uint8_t *)arg_ptr, (int)arg_int);
            if(bytesSent > 16) {
                taskManager.yieldForMicros(0);
                bytesSent = 0;
            }
            break;
        case U8X8_MSG_BYTE_START_TRANSFER:
            U8g2Drawable::pWire->beginTransmission(u8x8_GetI2CAddress(u8x8)>>1);
            break;
        case U8X8_MSG_BYTE_END_TRANSFER:
            U8g2Drawable::pWire->endTransmission();
            break;
        case U8X8_MSG_BYTE_INIT:
        case U8X8_MSG_BYTE_SET_DC:
            break;
        default:
            return 0;
    }
    return 1;
}
#endif // WANT_TASK_MANAGER_FRIENDLY_YIELD

U8g2Drawable::U8g2Drawable(U8G2 *u8g2, TwoWire* wireImpl) : u8g2(u8g2) {
#if WANT_TASK_MANAGER_FRIENDLY_YIELD == 1
    pWire = wireImpl;
    if(wireImpl) {
        u8g2->getU8x8()->byte_cb = u8g2_byte_with_yield;
    }
#endif
}

void U8g2Drawable::internalDrawText(const Coord &where, const void *font, int mag, const char *text) {
    u8g2->setFont(safeGetFont(font));
    u8g2->setFontMode(drawColor == 2);
    auto extraHeight = u8g2->getMaxCharHeight();
    u8g2->setDrawColor(drawColor);
#ifdef TC_USE_UTF_8_ENCODING
    u8g2->drawUTF8(where.x, where.y + extraHeight, text);
#else
    u8g2->setCursor(where.x, where.y + extraHeight);
    u8g2->print(text);
#endif
}

void U8g2Drawable::drawBitmap(const Coord &where, const DrawableIcon *icon, bool selected) {
    u8g2->setDrawColor(backgroundColor);
    u8g2->drawBox(where.x, where.y, icon->getDimensions().x, icon->getDimensions().y);
    u8g2->setDrawColor(drawColor);
    if(icon->getIconType() == DrawableIcon::ICON_XBITMAP) {
#if defined(__AVR__) || defined(ESP8266)
        u8g2->drawXBMP(where.x, where.y, icon->getDimensions().x, icon->getDimensions().y, icon->getIcon(selected));
#else
        u8g2->drawXBM(where.x, where.y, icon->getDimensions().x, icon->getDimensions().y, icon->getIcon(selected));
#endif
    }
}

void U8g2Drawable::drawXBitmap(const Coord &where, const Coord &size, const uint8_t *data) {
    u8g2->setDrawColor(backgroundColor);
    u8g2->drawBox(where.x, where.y, size.x, size.y);
    u8g2->setDrawColor(drawColor);
#if defined(__AVR__) || defined(ESP8266)
    u8g2->drawXBMP(where.x, where.y, size.x, size.y, data);
#else
    u8g2->drawXBM(where.x, where.y, size.x, size.y, data);
#endif
}

void U8g2Drawable::drawBox(const Coord &where, const Coord &size, bool filled) {
    u8g2->setDrawColor(drawColor);
    if(filled) {
        u8g2->drawBox(where.x, where.y, size.x, size.y);
    }
    else {
        u8g2->drawFrame(where.x, where.y, size.x, size.y);
    }
}

void U8g2Drawable::drawCircle(const Coord &where, int radius, bool filled) {
    u8g2->setDrawColor(drawColor);
    u8g2->drawCircle(where.x, where.y, radius);
}

void U8g2Drawable::drawPolygon(const Coord *points, int numPoints, bool filled) {
    if(numPoints == 2) {
        u8g2->drawLine(points[0].x, points[0].y, points[1].x, points[1].y);
    }
    else if(numPoints == 3) {
        u8g2->drawTriangle(points[0].x, points[0].y, points[1].x, points[1].y, points[2].x, points[2].y);
    }
}


void U8g2Drawable::transaction(bool isStarting, bool redrawNeeded) {
    if(isStarting) {
        u8g2->setFontPosBottom();
        u8g2->setFontRefHeightExtendedText();
    }
    else if(redrawNeeded) {
        u8g2->sendBuffer();
    }
}

Coord U8g2Drawable::internalTextExtents(const void *font, int mag, const char *text, int *baseline) {
    u8g2->setFont(safeGetFont(font));
    if(baseline) *baseline = (int)u8g2->getFontDescent();
#ifdef TC_USE_UTF_8_ENCODING
    return Coord(u8g2->getUTF8Width(text), u8g2->getMaxCharHeight());
#else
    return Coord(u8g2->getStrWidth(text), u8g2->getMaxCharHeight());
#endif
}

void U8g2Drawable::drawPixel(uint16_t x, uint16_t y) {
    u8g2->drawPixel(x, y);
}

UnicodeFontHandler* U8g2Drawable::createFontHandler() {
    return new UnicodeFontHandler(newU8G2TextPipeline(u8g2), ENCMODE_UTF8);
}

#include "ThemeMonoBorderedBuilder.h"
#include <Fonts/OpenSansRegular7pt.h>
#include <Fonts/OpenSansRegular8pt.h>

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "Mkr Ethernet OLED", "2d36dbe4-4892-410f-b0d6-775ec3637f6f" };
IoAbstractionRef ioexp_io8574 = ioFrom8574(0x20, 6);
U8G2_SH1106_128X64_NONAME_F_HW_I2C gfx(U8G2_R0, -1, 12, 13);
U8g2Drawable gfxDrawable(&gfx, &Wire);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);

// Declaring as extern any custom RtCalls and scroll variables
extern char ScrollRam[];

// Declaring any arrays used by enum/list items
const char* SettingsModeEnumEntries[] = { "Fully ON", "Fully OFF", "Vacation" };

void buildMenu(TcMenuBuilder& builder) {
    builder.usingDynamicEEPROMStorage()
        .analogBuilder(MENU_KITCHEN_ID, "Kitchen", DONT_SAVE, NoMenuFlags, 0, nullptr)
            .offset(-55).divisor(1).step(1).maxValue(255).unit("oC").endItem()
        .analogBuilder(MENU_LOUNGE_ID, "Lounge", DONT_SAVE, NoMenuFlags, 0, nullptr)
            .offset(-55).divisor(1).step(1).maxValue(255).unit("oC").endItem()
        .analogBuilder(MENU_HALLWAY_ID, "Hallway", DONT_SAVE, NoMenuFlags, 0, nullptr)
            .offset(-55).divisor(1).step(1).maxValue(255).unit("oC").endItem()
        .subMenu(MENU_SETTINGS_ID, "Settings", NoMenuFlags, nullptr)
            .analogBuilder(MENU_SETTINGS_TEMP_DESIRED_ID, "Temp desired", ROM_SAVE, NoMenuFlags, 0, nullptr)
                .offset(0).divisor(1).step(1).maxValue(255).unit("Unit").endItem()
            .enumItem(MENU_SETTINGS_MODE_ID, "Mode", ROM_SAVE, SettingsModeEnumEntries, 3, NoMenuFlags, 0, nullptr)
            .boolItem(MENU_SETTINGS_PROTECTION_ID, "Protection", ROM_SAVE, NAMING_ON_OFF, NoMenuFlags, false, nullptr)
            .actionItem(MENU_SETTINGS_EMERGENCY_OFF_ID, "Emergency off", NoMenuFlags, nullptr)
            .endSub()
        .subMenu(MENU_OTHER_TYPES_ID, "Other Types", NoMenuFlags, nullptr)
            .textItem(MENU_OTHER_TYPES_TEXT_ID, "Text", ROM_SAVE, 10, NoMenuFlags, "", nullptr)
            .rgb32Item(MENU_OTHER_TYPES_R_G_B_ITEM_ID, "RGB Item", ROM_SAVE, false, NoMenuFlags, RgbColor32(0, 0, 0), nullptr)
            .scrollChoiceBuilder(MENU_OTHER_TYPES_FOODS_ID, "Foods", ROM_SAVE, NoMenuFlags, 0, nullptr).fromRamChoices(ScrollRam, 5, 10).endItem()
            .endSub();
}

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setEepromStorageMode(TC_STORE_ROM_DYNAMIC);
    TcMenuBuilder builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // Code generated by plugins and new operators.
        gfx.begin();
        renderer.setUpdatesPerSecond(4);
        switches.init(ioexp_io8574, SWITCHES_NO_POLLING, true);
        menuMgr.initForEncoder(&renderer, &*getMenuItemById(MENU_KITCHEN_ID), 1, 2, 0);
        installMonoBorderTitleTheme(renderer, MenuFontDef(&OpenSansRegular7pt, 0), MenuFontDef(&OpenSansRegular8pt, 0), true, BaseGraphicalRenderer::TITLE_FIRST_ROW, true);
}

