/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <tcUnicodeHelper.h>
#include "tcMenuU8g2.h"
#include <ScrollChoiceMenuItem.h>
#include <RuntimeMenuItem.h>
#include <IoAbstractionWire.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern U8G2_SH1106_128X64_NONAME_F_HW_I2C gfx;
extern U8g2Drawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern const UnicodeFont OpenSansRegular7pt[];
extern const UnicodeFont OpenSansRegular8pt[];

// Any externals needed by IO expanders, EEPROMs etc
extern IoAbstractionRef ioexp_io8574;

// Global Menu Item exports
extern ScrollChoiceMenuItem menuOtherTypesFoods;
extern Rgb32MenuItem menuOtherTypesRGBItem;
extern TextMenuItem menuOtherTypesText;
extern BackMenuItem menuBackOtherTypes;
extern SubMenuItem menuOtherTypes;
extern ActionMenuItem menuSettingsEmergencyOff;
extern BooleanMenuItem menuSettingsProtection;
extern EnumMenuItem menuSettingsMode;
extern AnalogMenuItem menuSettingsTempDesired;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern AnalogMenuItem menuHallway;
extern AnalogMenuItem menuLounge;
extern AnalogMenuItem menuKitchen;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuKitchen; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION


#endif // MENU_GENERATED_CODE_H
