/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino 32bit ARM by TcMenu 4.5.0 on 2026-01-08T12:05:23.935272Z.

#include <tcMenu.h>
#include "mkrEthernetOled_menu.h"
#include "ThemeMonoBorderedBuilder.h"
#include <Fonts/OpenSansRegular7pt.h>
#include <Fonts/OpenSansRegular8pt.h>

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "MKR eInk", "2d36dbe4-4892-410f-b0d6-775ec3637f6f" };
IoAbstractionRef ioexp_io8574 = ioFrom8574(0x20, 6);
U8G2_SH1106_128X64_NONAME_F_HW_I2C gfx(U8G2_R0, -1, 12, 13);
U8g2Drawable gfxDrawable(&gfx, &Wire);
GraphicsDeviceRenderer renderer(30, applicationInfo.name, &gfxDrawable);

// Global Menu Item declarations
extern char ScrollRam[];
const AnyMenuInfo minfoOtherTypesFoods = { "Foods", 12, 23, 0, NO_CALLBACK };
ScrollChoiceMenuItem menuOtherTypesFoods(&minfoOtherTypesFoods, 0, ScrollRam, 10, 5, nullptr, INFO_LOCATION_PGM);
const AnyMenuInfo minfoOtherTypesRGBItem = { "RGB Item", 11, 19, 0, NO_CALLBACK };
Rgb32MenuItem menuOtherTypesRGBItem(&minfoOtherTypesRGBItem, RgbColor32(0, 0, 0), false, &menuOtherTypesFoods, INFO_LOCATION_PGM);
const AnyMenuInfo minfoOtherTypesText = { "Text", 10, 9, 0, NO_CALLBACK };
TextMenuItem menuOtherTypesText(&minfoOtherTypesText, "", 10, &menuOtherTypesRGBItem, INFO_LOCATION_PGM);
const SubMenuInfo minfoOtherTypes = { "Other Types", 9, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackOtherTypes(&minfoOtherTypes, &menuOtherTypesText, INFO_LOCATION_PGM);
SubMenuItem menuOtherTypes(&minfoOtherTypes, &menuBackOtherTypes, nullptr, INFO_LOCATION_PGM);
const AnyMenuInfo minfoSettingsEmergencyOff = { "Emergency off", 8, 0xffff, 0, NO_CALLBACK };
ActionMenuItem menuSettingsEmergencyOff(&minfoSettingsEmergencyOff, nullptr, INFO_LOCATION_PGM);
const BooleanMenuInfo minfoSettingsProtection = { "Protection", 7, 8, 1, NO_CALLBACK, NAMING_ON_OFF };
BooleanMenuItem menuSettingsProtection(&minfoSettingsProtection, false, &menuSettingsEmergencyOff, INFO_LOCATION_PGM);
const char enumStrSettingsMode_0[] = "Fully ON";
const char enumStrSettingsMode_1[] = "Fully OFF";
const char enumStrSettingsMode_2[] = "Vacation";
const char* const enumStrSettingsMode[]  = { enumStrSettingsMode_0, enumStrSettingsMode_1, enumStrSettingsMode_2 };
const EnumMenuInfo minfoSettingsMode = { "Mode", 6, 6, 2, NO_CALLBACK, enumStrSettingsMode };
EnumMenuItem menuSettingsMode(&minfoSettingsMode, 0, &menuSettingsProtection, INFO_LOCATION_PGM);
const AnalogMenuInfo minfoSettingsTempDesired = { "Temp desired", 5, 4, 255, NO_CALLBACK, 0, 1, "Unit" };
AnalogMenuItem menuSettingsTempDesired(&minfoSettingsTempDesired, 0, &menuSettingsMode, INFO_LOCATION_PGM);
const SubMenuInfo minfoSettings = { "Settings", 4, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSettings(&minfoSettings, &menuSettingsTempDesired, INFO_LOCATION_PGM);
SubMenuItem menuSettings(&minfoSettings, &menuBackSettings, &menuOtherTypes, INFO_LOCATION_PGM);
const AnalogMenuInfo minfoHallway = { "Hallway", 3, 0xffff, 255, NO_CALLBACK, -55, 1, "oC" };
AnalogMenuItem menuHallway(&minfoHallway, 0, &menuSettings, INFO_LOCATION_PGM);
const AnalogMenuInfo minfoLounge = { "Lounge", 2, 0xffff, 255, NO_CALLBACK, -55, 1, "oC" };
AnalogMenuItem menuLounge(&minfoLounge, 0, &menuHallway, INFO_LOCATION_PGM);
const AnalogMenuInfo minfoKitchen = { "Kitchen", 1, 0xffff, 255, NO_CALLBACK, -55, 1, "oC" };
AnalogMenuItem menuKitchen(&minfoKitchen, 0, &menuLounge, INFO_LOCATION_PGM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(true);
    // Code generated by plugins and new operators.
    gfx.begin();
    renderer.setUpdatesPerSecond(4);
    switches.init(ioexp_io8574, SWITCHES_NO_POLLING, true);
    menuMgr.initForEncoder(&renderer, &menuKitchen, 1, 2, 0);
    installMonoBorderTitleTheme(renderer, MenuFontDef(&OpenSansRegular7pt, 0), MenuFontDef(&OpenSansRegular8pt, 0), true, BaseGraphicalRenderer::TITLE_FIRST_ROW, true);
}

