/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <SSD1306Ascii.h>
#include <SSD1306AsciiAvrI2c.h>
#include "ssd1306asciiRenderer.h"
#include <JoystickSwitchInput.h>
#include <IoAbstraction.h>
#include <EepromAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern SSD1306AsciiAvrI2c gfx;
extern SSD1306AsciiRenderer renderer;
extern MultiIoAbstraction joystickMultiIo;
extern AnalogJoystickToButtons joystickIoXAxis;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern ActionMenuItem menuSettingsSaveAll;
extern EnumMenuItem menuSettingsDifficulty;
extern AnalogMenuItem menuSettingsFrameRate;
extern BackMenuItem menuBackSettings;
extern SubMenuItem menuSettings;
extern AnalogMenuItem menuHighScore;
extern ActionMenuItem menuStartGame;
extern ActionMenuItem menuInstructions;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuInstructions; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION onInstructions(int id);
void CALLBACK_FUNCTION onSave(int id);
void CALLBACK_FUNCTION onStartGame(int id);

#endif // MENU_GENERATED_CODE_H
