// TcMenu Generated Locale File, do not edit this file. Locale fr
// Never include directly, always include the langSelect header

#define TC_I18N_MENU_2_NAME "Flotter"
#define TC_I18N_MENU_8_NAME "Oui Non"
#define TC_I18N_MENU_5_NAME "Paramètres"
#define TC_I18N_PROJECT_NAME "Tableau de bord"
#define TC_I18N_MENU_7_NAME "Couleur"
#define TC_I18N_MENU_3_ENUM_1 "Pâtes"
#define TC_I18N_MENU_3_ENUM_2 "Pizza"
#define TC_I18N_MENU_1_NAME "Analogique"
#define TC_I18N_MENU_4_NAME "Power"
#define TC_I18N_MENU_1_UNIT "V"
#define TC_I18N_MENU_3_ENUM_0 "Salade"
#define TC_I18N_MENU_6_NAME "Action"
#define TC_I18N_MENU_3_NAME "Le Enum"
