/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include<IoAbstraction.h>
#include<Wire.h>
#include<tcMenu.h>

#include <Wire.h>
#include <tcMenuLiquidCrystal.h>
#include <IoAbstractionWire.h>
#include "RemoteConnector.h"


#define ENCODER_PIN_A 0
#define ENCODER_PIN_B 0
#define ENCODER_PIN_OK 0

#define LCD_RS 0
#define LCD_EN 2
#define LCD_D4 4
#define LCD_D5 5
#define LCD_D6 6
#define LCD_D7 7
#define LCD_WIDTH 20
#define LCD_HEIGHT 4
#define LCD_PWM_PIN -1
#define LCD_I2C_ADDR 0x20
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

extern const char applicationName[];


// all callback functions must have this define on them, it is what the menu designer looks for.
#define CALLBACK_FUNCTION

// Forward reference all the callback functions.

void CALLBACK_FUNCTION onAnalog1(int menuId);
void CALLBACK_FUNCTION onSwitch1(int menuId);


// Export all the menu items so they are visible in sketches.

extern AnalogMenuItem menuVoltage;

extern BooleanMenuItem menuMoreOptions;

extern SubMenuItem menuSubMenu;

extern EnumMenuItem menuChoices;

extern BooleanMenuItem menuSwitch1;

extern AnalogMenuItem menuAnalog1;



void setupMenu();

#endif /* header include check */
